<?php

/**
 * .htaccess requires an absolute path
 * to an .htpasswd file. Run this script
 * to configure the /admin/ directory password
 * protection per server.
 */
if (file_put_contents(
    "../admin/.htaccess", '##############################################
#### GENERATED BY SCRIPT -- DO NOT MODIFY ####
##############################################

Authtype Basic
AuthName "Magnificent Admin Portal"
AuthUserFile ' . $_SERVER["DOCUMENT_ROOT"] . '/admin/.htpasswd
Require valid-user'
)) {
    echo "Updated /admin/.htaccess successfully.";
} else
    echo "Error updating /admin/.htaccess.";
?>